name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker compose build

      - name: Lint code
        run: docker compose run --rm server flake8

      - name: Run tests
        run: docker compose run --rm server pytest
